### PR TITLE
Strong name the assemblies

### LINKED ISSUE #481: StrongNamed version of the assembly
**Is your feature request related to a problem? Please describe.**
A codebase with a lot of use of `InternalsVisibleTo` so all assemblies must be signed.

**Describe the solution you'd like**
Either sign the final assembly or have a signed nuget version as some other libs do.

**Describe alternatives you've considered**
Is not possible to load a non signed assembly from a signed assembly, at compile time at least...

**Additional context**

---
Please upvote :+1: this issue if you are interested in it.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Revival of https://github.com/spectreconsole/spectre.console/pull/687

fixes #481 

- [x] I have read the [Contribution Guidelines](https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md)
- [x] I have commented on the issue above and discussed the intended changes
- [x] A maintainer has signed off on the changes and the issue was assigned to me
- [x] All newly added code is adequately covered by tests
- [x] All existing tests are still running without errors
- [x] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

## Changes

Adds a strong name key pair and signs all assemblies using the .snk file. Temporarily suppresses one warning until Spectre.Verify.Extensions is signed (in a separate PR).

---
Please upvote :+1: this pull request if you are interested in it.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Huge thanks to @sebastienros for the original PR.

**Comment by sebastienros** [comment]
Yours is better, you know how to use msbuild ;)

**Review by sebastienros — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
Companion PR: https://github.com/spectresystems/spectre.verify.extensions/pull/10

Once that merges and we update Spectre.Verify.Extensions in this repo, we can remove the NoWarn here:
https://github.com/KirillOsenkov/spectre.console/blob/6116af384458dc6acc7b887617e7aec45c703d86/src/Tests/Directory.Build.props#L8

I was also wondering why there's a separate Directory.Build.props in the Tests directory. All the three properties that it sets are already set by the parent. However the parent Directory.Build.props will not be automatically imported. If you want it to be imported you need to add: `<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props'))" />`

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Pull request merged**
