### PR TITLE
Enhance the style of the checkboxes for multi-selection

### PR DESCRIPTION
**Pull request by davide-pi**
# Description

Enhance the style of the checkboxes for multi-selection by applying the selected style, if available, to the checkboxes that are currently selected.

# Examples

Old or without style specified
image

With multiselection style specified with `.HighlightStyle(new Style(Color.Red))`
image

# Reason

I would like the `X` on the selected checkboxes to have the same style as the multiselection highlight to avoid any mismatched color combinations

---
Please upvote :+1: this pull request if you are interested in it.

### CODE REVIEW

**Comment by davide-pi** [comment]
@microsoft-github-policy-service agree

**Comment by SypherrDev** [comment]
I truly hope this gets merged, it's truly painful for designing that the color isn't matching.

**Comment by davide-pi** [comment]
Thansk @SypherrDev, I'm waiting for someone review to be able to complete these PR. 😃

**Comment by patriksvensson** [comment]
@davide-pi Could you perfom a rebase on your branch instead of a merge as per our [CONTRIBUTING.md](https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md#other-general-information) instructions?

**Comment by davide-pi** [comment]
Sure sorry @patriksvensson. Fixed thanks!

**Review by patriksvensson — APPROVED** [review]

**Pull request merged**
