### PR TITLE
Fix issue 1153 on expanded tree

### PR DESCRIPTION
**Pull request by davide-pi**
# Description

Fix issue #1153

# Examples

| Before fix| After fix |
|--|--|
| image | image |

# To Test

To test the fix the following code was used.
Is sufficient to put it into the `Main` method of the `Program.cs` in the `Spectre.Console.Analyzer.Sandbox` to see the difference between expanded and not expanded trees.

> _**NOTE:** Curly brackets are used to simplify code duplication for test purposes only_

```csharp
      {
            AnsiConsole.MarkupLine("Expaded [green]default true[/]");
            var root = new Tree("root");
            root.AddNode("node1");
            root.AddNode("node2");
            AnsiConsole.Render(root);
        }

        AnsiConsole.MarkupLine("");
        AnsiConsole.MarkupLine("");

        {
            AnsiConsole.MarkupLine("Expaded [red]false[/] in init");
            var root = new Tree("root") { Expanded = false };
            root.AddNode("node1");
            root.AddNode("node2");
            AnsiConsole.Render(root);
        }
        AnsiConsole.MarkupLine("");
        {
            AnsiConsole.MarkupLine("Expaded [green]true[/] in init");
            var root = new Tree("root") { Expanded = true };
            root.AddNode("node1");
            root.AddNode("node2");
            AnsiConsole.Render(root);
        }

        AnsiConsole.MarkupLine("");
        AnsiConsole.MarkupLine("");

        {
            AnsiConsole.MarkupLine("Expaded [red]false[/] after init");
            var root = new Tree("root");
            root.Expanded = false;
            root.AddNode("node1");
            root.AddNode("node2");
            AnsiConsole.Render(root);
        }
        AnsiConsole.MarkupLine("");
        {
            AnsiConsole.MarkupLine("Expaded [green]true[/] after init");
            var root = new Tree("root");
            root.Expanded = true;
            root.AddNode("node1");
            root.AddNode("node2");
            AnsiConsole.Render(root);
        }
```

---
Please upvote :+1: this pull request if you are interested in it.

### CODE REVIEW

**Comment by davide-pi** [comment]
@microsoft-github-policy-service agree

**Review by patriksvensson — APPROVED** [review]
LGTM 👍

**Comment by patriksvensson** [comment]
@davide-pi Looks good to me, but the PR must be rebased against main before we can merge it

**Comment by davide-pi** [comment]
Thanks @patriksvensson  I've merged the PR with the las changes in main!

**Pull request merged**
