### PR TITLE
Work done to allow user to update table cell. 

### PR DESCRIPTION
**Pull request by RedEyedDog**
Issue URL: https://github.com/spectreconsole/spectre.console/issues/544

Hope everything is up to standard. 

let me know of any changes.

### CODE REVIEW

**Comment by RedEyedDog** [comment]
> @RedEyedDog Could you rebase this against upstream `main` so we can see that all checks pass?

I'm not sure what you mean sorry is it out of date with master?

**Comment by patriksvensson** [comment]
@RedEyedDog Yes exactly. Sync your main branch locally, switch to your feature branch and write `git rebase main` and then a `git push --force-with-lease`.

**Comment by RedEyedDog** [comment]
> @RedEyedDog Yes exactly. Sync your `main` branch locally, switch to `updatecell` branch and write `git rebase main` followed by a `git push --force-with-lease`.

Hey its telling me I am up to date ?

**Comment by patriksvensson** [comment]
@RedEyedDog  It is not, so make sure that your fork is up to date before doing the rebase, and make sure you've done a `git pull` on the `main` branch of your fork before as well.

image

**Comment by RedEyedDog** [comment]
@patriksvensson ok I have done that. Sorry this will be my first contribution to an open source project. POP MY CHERRY ;)

**Comment by patriksvensson** [comment]
@RedEyedDog Great! Running CI again.

Welcome to the world of OSS btw! 🎉

**Review by patriksvensson — APPROVED** [review]
LGTM (looks good to me) 👍

**Comment by RedEyedDog** [comment]
Thanks for all your help :) till next time

**Pull request merged**
