### PR TITLE
Issue 411 - Alias for branches

### LINKED ISSUE #411: Alias for Branches
Would it be possible to add command like configurations, e.g. Alias and Description for branches? I am having an issue where my branch names are becoming fairly long, and would improve ease of use of my CLI if descriptions and aliases for branches were avaialable.

```c#
app.Configure(config =>
{
  config.AddBranch<AddSettings>("add", add =>
  {
    add.Alias("a") // <-- or something similar
    add.SetDescription("Add something");
    add.AddCommand<AddPackageCommand>("package");
    add.AddCommand<AddReferenceCommand>("reference");
  })
});
```

### PR DESCRIPTION
**Pull request by ilyahryapko**
Hello there!

Fixes #411 - Adding aliases to branches

Sample usage
```csharp
var app = new CommandApp();
app.Configure(config =>
{
    config.AddBranch<AnimalSettings>("animal", animal =>
    {
        animal.AddCommand<DogCommand>("dog");
        animal.AddCommand<HorseCommand>("horse");
    }).WithAlias("a");
});
```

First PR here (and ever in open source). Any help or guidance appreciated

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1131) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1131) before we can accept your contribution.<br/><br/>:x: ilyahryapko [sign now](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1131)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/spectreconsole/spectre.console?pullRequest=1131) it.</sub>

**Comment by FrankRay78** [comment]
Thank you @ilyahryapko for the PR, I'll make time to review this shortly.

If you make a comment on the issue this addresses (https://github.com/spectreconsole/spectre.console/issues/411) then I will be able to assign it to you (I can't do that until you've participated in the thread, for some reason...). nb. It doesn't matter if you don't, it's just some people like to be credited on the issue,

**Review by FrankRay78 — APPROVED** [review]

**Comment by FrankRay78** [comment]
A very high quality submission @ilyahryapko, many thanks and it's merged now.

Unrelated to your work but becoming obvious to me in the review process, has emerged this issue: https://github.com/spectreconsole/spectre.console/issues/1157   

Let me know if it takes your fancy....

**Comment by ilyahryapko** [comment]
Thanks for review, much appreciated!

> Let me know if it takes your fancy....
Was it okay to merge my PR since that issue occured right after?
Anyway, I'll try to look at that in a week or so

**Comment by FrankRay78** [comment]
> @FrankRay78 Thanks for review, much appreciated!
> 
> > Let me know if it takes your fancy....
> 
> Was it okay to merge my PR since that issue occured right after? Anyway, I'll try to look at that in a week or so

I double checked and the logic to flag a duplicate alias across multiple commands was erroneous before branches were even considered, and so I felt it was better treated as a new issue, particularly since you implemented the branch alias in exactly the same style as per command alias's.  

No obligation to look into the new issue, just that I will give it to you first if you wish, as it relates to the handling of alias's

**Comment by ilyahryapko** [comment]
@FrankRay78 hey, sorry, I don't have enough time and overall capacity right now, so issue could be freely reassigned to anyone else :(

**Pull request merged**
