### PR TITLE
build: set nuget package as dev dependency

### PR DESCRIPTION
**Pull request by lonix1**
[Reference](https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference)

closes: #932

### CODE REVIEW

**Comment by lonix1** [comment]
Hope I did it properly, I've always had trouble with the github PR thing. :)

**Review by patriksvensson — APPROVED** [review]
LGTM!

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Comment by 0xced** [comment]
Here are some example of actual development dependencies:
* [MinVer](https://github.com/adamralph/minver)
* [Microsoft.SourceLink.GitHub](https://www.nuget.org/packages/Microsoft.SourceLink.GitHub)
* [Costura](https://github.com/Fody/Costura)
* [Microsoft.Windows.CsWin32](https://github.com/microsoft/CsWin32)

I don't see how Spectre.Console qualifies as a development dependency. 🤔 I think this pull request should be reverted.

**Comment by 0xced** [comment]
Oh, I see that the original issue was about the `Spectre.Console.Analyzer` package but this pull request applied the `DevelopmentDependency` on `Spectre.Console.csproj` instead of `Spectre.Console.Analyzer.csproj`.

**Comment by patriksvensson** [comment]
Yeah. Not sure what I was thinking to be honest. It's the Spectre.Console.Analyzer package that should be set as a dev dependency.

**Comment by 0xced** [comment]
I opened #950 for you to just have to click the merge button. 😉

**Comment by nils-a** [comment]
No worries @lonix1, it's all @patriksvensson|s fault for merging it in 🤣 🤣 

Seriously, though: I feel you're a hero for opening a PR. 👍 
(And: "He, who never created a PR with a mistake in it" can throw the first stone.)

**Pull request merged**
