### PR TITLE
WIP Tab completion for CLI

### LINKED ISSUE #267: Tab completion for CLI
I was going to toy around with adding powershell or bash tab completion for my app, but it occurred to me that it might be possible (and maybe even easier) to bake this in. I'd 

The way some tools work is they provide something like a `completion` command that accepts the list of currently typed arguments (e.g. if I was typing `git checkout sp[tab]` it would run `git completion checkout sp` and the application would supply the tab information. 

My Saturday night plan for investigation the feasibility would be for simple things like enums and bools to automatically return the valid values. But for strings it would work like `ParameterValidationAttribute` where you could have

```
public abstract CompletionResult Complete(ICommandParameterInfo info, object? value);
```

And you'd mark up your settings appropriately. You'd want services to be injected though. TBH I'm not sure if the validation code allows that as is.

## Reading
* [Command-line tab completion for Octopus CLI](https://octopus.com/blog/tab-completion-for-the-octopus-cli)
* [How to enable TAB completion for the .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)

### PR DESCRIPTION
**Pull request by Jawz84**
The goal of this pull request is to add out-of-the-box completer functionality to Spectre.Console, as suggested in #267.

The approach will be to mimic what a tool like `dotnet complete` does. As a result, the completion scripts that people can use, will be analogous to those for `dotnet complete`.

### CODE REVIEW

**Comment by Jawz84** [comment]
@patriksvensson @phil-scott-78 Do you feel am I taking this in the right direction? Today's start, to me, felt promising. Let me know your thoughts, and feel free to add (failing) tests to provide more specific direction.

**Comment by Jawz84** [comment]
I forgot to catch the actual parser error, so... I was accidentally muting an index out of bounds exception.. fixed now.

**Comment by phil-scott-78** [comment]
I'm going to pul this down tonight and play with it. So far it looks really cool.

One scenario that I was thinking about was being able to add a service to commands to specify valid values when they are resolved. E.g. when I type `git add a<TAB>` the add verb is clever enough to suggest dirty files starting with the letter a.

**Comment by Jawz84** [comment]
@phil-scott-78 I'm not entirely sure yet how to add what you mentioned above. Could you provide a pseudo code draft?

I added option parameter support and some more tests.

**Comment by phil-scott-78** [comment]
So my thought was given this settings

```csharp
public class FooCommandSettings : CommandSettings
{
    [CommandArgument(0, "[QUX]")]
    [Description("The qux value.")]
    public string Qux { get; set; }
}
```

Let's assume Qux might be a list of *.qux files in the current folder or sub-folder.

Someone types in `myapp.exe p<TAB>` the app would be able to autocompletion info in the form of all the files that are `p*.qux`. 

To implement perhaps would work like the `ParameterValidationAttribute

```csharp
public sealed class FileCompletionAttribute : ParameterValidationAttribute
{
    public override string[] Complete(CommandParameterContext context, string partialElement)
    {
        return GetQuxCompletions(partialElement);
    }
}



public class FooCommandSettings : CommandSettings
{
    [CommandArgument(0, "[QUX]")]
    [Description("The qux value.")]
    [FileCompletionAttribute]
    public string Qux { get; set; }
}
```

**Comment by Jawz84** [comment]
It's absolutely the next step and would be super cool to have. I'll have a look at where this would fit, thanks for the input, appreciate it!

**Comment by FrankRay78** [comment]
Hello @Jawz84, I'm just checking in to see if you made any further progress with this PR?

**Comment by Jawz84** [comment]
Hi Frank, thank you for checking in. I'm afraid life happened and I have since not continued the PR.
I don't think I will continue it either. It's been so long and lots of other things are happening.
Sorry to disappoint.

Met vriendelijke groet,

Jos Koelewijn
________________________________

**Comment by FrankRay78** [comment]
Thanks for replying @Jawz84 , it's no disappointment and all contributions, even unmerged WIP PRs are appreciated. I was just doing some housekeeping across the open issues and PRs to check on any progress.

Regarding tab completion, and whilst I don't know anything about MacOS and Linux, it seems more involved than it first appears:  https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete    ie. each shell seems to need custom configuration manually added before tab completion actually works

Anyhow, I'm going to close this PR given your comment above and you can always come back to it later if you so desire.  Or not. Take care

**Comment by Jawz84** [comment]
Thank you Frank!

________________________________

**Pull request closed without merging**
