### PR TITLE
Fixed render issue where writeline inside status caused corrupt output #415 #694

### PR DESCRIPTION
**Pull request by fredrikbentzen**
Issues: #415 #694

The problem was inside the method PositionCursor in LiveRenderable where the cursor (before the fix) just moved from to the bottom to the starting point without clearing the lines it passed through. This caused the statusmessage to still be visible when the writeline message was the first renderable to be rendered and its second/wrapped line (the line where the statusmessage still was present) was shorter than the statusmessage.

I've fixed it by clearing the lines it passes through when re-positioning the cursor for re-rendering.

Additional context, illustrations and issue description can be found in the referenced issues.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1132) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1132) before we can accept your contribution.<br/><br/>:x: fredrikbentzen [sign now](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1132)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/spectreconsole/spectre.console?pullRequest=1132) it.</sub>

**Comment by mscottford** [comment]
I'd love to see this get merged in. Is there a way that I can help resolve any blockers that are standing in the way of doing so?

**Comment by patriksvensson** [comment]
@mscottford Absolutely. I'll take a look at it tomorrow.

**Review by patriksvensson — APPROVED** [review]
Looks good to me! 👍

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Pull request merged**
