### PR TITLE
Async overloads for AnsiConsole Prompt/Ask/Confirm.

### PR DESCRIPTION
**Pull request by tmds**
@patriksvensson ptal.

---
Please upvote :+1: this pull request if you are interested in it.

### CODE REVIEW

**Comment by tmds** [comment]
@patriksvensson ptal.

**Comment by patriksvensson** [comment]
@tmds Sorry for taking time with this; currently a bit behind on the backlog. Will try to take a look at this tonight.

**Comment by mbursill** [comment]
This is very useful. Would love to see it merged.

**Comment by FrankRay78** [comment]
I'll take a look at this @tmds

**Comment by FrankRay78** [comment]
Dear @spectreconsole/maintainers, what's our policy on unit test coverage when adding Async overloads to existing functionality.

The code in this PR is clear, well structured, and high-quality. However, it doesn't contain any unit tests.

We have extensive unit test coverage of prompts here: [test/Spectre.Console.Tests/Unit/Prompts](https://github.com/spectreconsole/spectre.console/tree/bb72b44d607a5a2f407e910f6dc21f2a33c1b89a/test/Spectre.Console.Tests/Unit/Prompts), however they exercise the current (non-async) calls.

I don't think it makes sense to duplicate the 100-something existing unit tests for these async extensions, however equally I don't want to merge this until I've checked it's ok 'as-is' without tests.

What are your thoughts?

**Review by FrankRay78 — APPROVED** [review]
Good quality contribution, however waiting on feedback as to whether we need unit test coverage when adding async overloads.

**Comment by FrankRay78** [comment]
> This is very useful. Would love to see it merged.

@mbursill Do you have a code example of how you'd like to use the async overloads, out of interest?

**Comment by FrankRay78** [comment]
@tmds - what is the usage for an async prompt? I need some help understanding why a synchronous user prompt should be extended to be async. I'm not saying there isn't a need, but I need a working code snippet illustrating the motivation behind this PR please.

**Comment by tmds** [comment]
> @tmds - what is the usage for an async prompt? I need some help understanding why a synchronous user prompt should be extended to be async. I'm not saying there isn't a need, but I need a working code snippet illustrating the motivation behind this PR please.

The `CancellationToken` I'm passing is the one from https://github.com/dotnet/command-line-api that informs me the user has requested the app to terminate via Ctrl+C. As part of the termination, I want some things to get cleaned-up/Disposed.

**Comment by FrankRay78** [comment]
@tmds ok thanks for replying after so much time. Apologies, the widgets aren't my usual area of expertise and the other maintainers are quite busy to ask. I noticed your PR which looked like a good quality contribution and taken it on myself to review/merge. I think I understand the usage now. I do plan to get this one over the line.

**Comment by tmds** [comment]
No worries, @FrankRay78. Thanks for picking this up!

**Comment by patriksvensson** [comment]
@FrankRay78 Unit tests are preferred so we'll know if we introduce regressions. But it's your call.

**Comment by 0xced** [comment]
We've been discussing with @FrankRay78 and I've been experimenting with an alternative approach to this issue. I think the async APIs actually don't make sense but the sync APIs need cancellation support. I've been working on an [obsolete-async-prompt-apis](https://github.com/0xced/spectre.console/tree/obsolete-async-prompt-apis) branch where I have added cancellation support for all the prompt APIs.

@tmds Would you mind checking out this branch, build from source and see if this approach solves your problem? If you need help building from source I can assist.

**Comment by tmds** [comment]
> I think the async APIs actually don't make sense but the sync APIs need cancellation support.

Can you explain why?

Because the `CancellationToken` gets triggered asynchronously, I don't think a sync implementation can do something "better" than an async one. I think the only difference is whether the caller gets non-blocking async behavior or whether the thread blocks when there is no input.

**Comment by 0xced** [comment]
> Because the `CancellationToken` gets triggered asynchronously, I don't think a sync implementation can do something "better" than an async one. I think the only difference is whether the caller gets non-blocking async behavior or whether the thread blocks when there is no input.

You're right, I'll scrap my branch and start over with only adding cancellation support to the synchronous APIs (which is still needed) but without touching the asynchronous APIs which are fine.

> I don't think it makes sense to duplicate the 100-something existing unit tests for these async extensions, however equally I don't want to merge this until I've checked it's ok 'as-is' without tests.
> 
> What are your thoughts?

> [!NOTE]
> The tests that matter for this pull request are in `src/Tests/Spectre.Console.Tests/Unit/AnsiConsoleTests.Prompt.cs` instead of `src/Tests/Spectre.Console.Tests/Unit/Prompts/*.cs` and their count is closer to 3 than to 100. 😉

What about modifying the existing tests like this, from fact to theory with both sync and async paths? I think it's still pretty readable.

Before:
```csharp
[Fact]
public void Should_Return_Correct_DateTime_When_Asked_US_Culture()
{
    // Given
    var console = new TestConsole().EmitAnsiSequences();
    console.Input.PushTextWithEnter("2/1/1998");

    // When
    var dateTime = console.Ask<DateTime>(string.Empty, CultureInfo.GetCultureInfo("en-US"));

    // Then
    dateTime.ShouldBe(new DateTime(1998, 2, 1));
}
```

After:
```csharp
[Theory]
[InlineData(true)]
[InlineData(false)]
public async Task Should_Return_Correct_DateTime_When_Asked_US_Culture(bool async)
{
    // Given
    var console = new TestConsole().EmitAnsiSequences();
    console.Input.PushTextWithEnter("2/1/1998");

    // When
    DateTime dateTime;
    if (async)
        dateTime = await console.AskAsync<DateTime>(string.Empty, CultureInfo.GetCultureInfo("en-US"));
    else
        dateTime = console.Ask<DateTime>(string.Empty, CultureInfo.GetCultureInfo("en-US"));

    // Then
    dateTime.ShouldBe(new DateTime(1998, 2, 1));
}
```

**Comment by FrankRay78** [comment]
@tmds - unfortunately, @0xced has been called away.  So I'm going to put my name down on this, with an intention of getting the PR over the line.  I'm about to pull down the branch and take a look. Short of more significant prompt refactoring @0xced had in mind, it looks like a few unit test changes is all that's required for this PR.  Do you agree, and if so, are you able to help with them? I can review and merge, when appropriate.

**Comment by FrankRay78** [comment]
This is now top of my list to get over the line @tmds.

I'll take a look at what unit test coverage we need, then it should be a trivial matter of updating your branch and pushing.

Then we can welcome you into the `Spectre.Console` git commit history 👏

**Comment by tmds** [comment]
hi @FrankRay78 , sorry for the unresponsiveness, it was a very busy time for me. If you can provide some guidance on the unit test coverage, we can try to get this merged by the end of next week.

**Review by FrankRay78 — APPROVED** [review]

**Comment by phil-scott-78** [comment]
I'm traveling, but I'd wager the attributes for AOT that were added might be at fault. I don't have a computer but I'm happy to answer any questions or review

**Comment by FrankRay78** [comment]
Hello @phil-scott-78, do you know if as a maintainer, whether I should be able to resolve the conflict of another users fork/branch, then force push it back? Or if the user will always need to do that themselves? The contribution is fully reviewed and good to merge.

**Comment by phil-scott-78** [comment]
@FrankRay78, I've done it in the past and I've had maintainers fix my stuff, but the submitting user needs to enable it on their end. 

At the end of the day, I always feel like as long as the user's original commit is still in the history plus a maintainer commit with the needed touch up, then it's all good.

**Comment by tmds** [comment]
> the submitting user needs to enable it on their end.

afaik it is enabled by default and you should be able to push to my branch.

I've resolved the conflicts by merging in the `main` branch.

I assume you're going to squash this PR when merging. If not, let me know if you want me to clean up the commit history.

**Comment by tmds** [comment]
Thanks for your help, @FrankRay78!

**Pull request merged**
