### PR TITLE
Fix navigation and editing

### LINKED ISSUE #466: Text prompt lacks standard UI controls
**Information**
 - OS: Windows / Linux
 - Version: 0.40.0
 - Terminal: conhost / Windows Terminal

**Describe the bug**
The text prompt doesn't seem to support Home, End or CursorKeys. 
On Windows, if you go multiline you are unable to delete further than the current line you are on. Linux this seems to work.

**To Reproduce**
`string name = AnsiConsole.Ask<string>("TestPrompt:>");`

**Expected behavior**
Standard console text editing behaviour works.

---
Please upvote :+1: this issue if you are interested in it.

### PR DESCRIPTION
**Pull request by atreyurock**
Fixes #466

### CODE REVIEW

**Comment by matkoch** [comment]
@phil-scott-78 could you give this another run?

**Comment by matkoch** [comment]
Why exactly?

Firefox-Fix navigation and editing by atreyurock · Pull Request #586 · spectreconsolespectre console-2022-04-05-DlW9HGQm@2x

**Comment by patriksvensson** [comment]
Same here:

image

**Comment by matkoch** [comment]
Just in case you don't know how comment histories work:

Firefox-Fix navigation and editing by atreyurock · Pull Request #586 · spectreconsolespectre console-2022-04-05-taYa5tjW@2x

Firefox-Fix navigation and editing by atreyurock · Pull Request #586 · spectreconsolespectre console-2022-04-05-T34juxd3@2x

Firefox-Fix navigation and editing by atreyurock · Pull Request #586 · spectreconsolespectre console-2022-04-05-ue8GcvdP@2x

**Comment by matkoch** [comment]
And FYI, there is nothing to agree for the CLA:

Firefox-CLA assistant-2022-04-05-3D9x7OaH@2x

**Comment by patriksvensson** [comment]
Wasn't very clear you weren't looking at the latest version. Will need to investigate what happened with the CLA.

**Comment by patriksvensson** [comment]
Looks like the CLA assistant fetches the CLA asynchronously, and they seem to be having problems at the moment. If you wait about 10-20 seconds, it should appear:

image

**Comment by patriksvensson** [comment]
Closing due to CLA not signed.

**Pull request closed without merging**
