### PR TITLE
Add a prompt that allows a selection of a row in a table

### PR DESCRIPTION
**Pull request by FantasyTeddy**
This PR adds a very basic version of a prompt that displays a table with a highlighted row representing the selection.

### CODE REVIEW

**Comment by patriksvensson** [comment]
Clsoing this since CLA has not been signed.

**Comment by FantasyTeddy** [comment]
I have signed the CLA again (it expired and I didn't notice).

Can this PR be opened again? I also rebased my changes onto the latest main branch.

**Comment by patriksvensson** [comment]
I don't seem to be able to reopen the PR.
Could you recreate it?

image

**Comment by FantasyTeddy** [comment]
Oh I didn't realize that fore-pushing will prevent you from reopening it.

I opened a new PR: #888.

**Pull request closed without merging**
