### PR TITLE
Remove period trimming

### LINKED ISSUE #902: Trimming periods off documentation
I was surprised that the help output chops periods off documentation.  Occasionally, I create commands that need a little more context than I can put into a single sentence, so I ended up with documentation that had several sentences -- the last sentence ends up with no period (even though I add it in my `DescriptionAttribute`).

I'm curious whether there's some standard or tradition that I'm unaware of that leads to this approach.  Would you consider making this an optional behavior (maybe as a part of the configuration of the `CommandApp`?)?

Thanks for all the work you've done here.  Spectre.Console is awesome!

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
- Add in configuration to toggle whether to trim trailing periods or not.
- Add in implementation.
- Add in tests with a configuration set to not trim trailing periods.

Fixes #902

### CODE REVIEW

**Comment by BenjaminMichaelis** [comment]
Is this all that is needed to fix this @patriksvensson ?

**Comment by patriksvensson** [comment]
The build problems should have been resolved now.
Could you rebase your PR branch against the main branch?

**Comment by BenjaminMichaelis** [comment]
Just rebased and added in a configuration

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Pull request merged**
