### PR TITLE
feat: Allow case-insensitive confirmation prompt

### LINKED ISSUE #1119: Add support for case insensitive confirmation
image
"Y" or "N" are not valid answers. Not a big problem, but it would be better to answers be case insensitive.

### PR DESCRIPTION
**Pull request by MartinZikmund**
closes #1119

Adding this for https://github.com/unoplatform/uno.check/issues/121 😉

### CODE REVIEW

**Review by patriksvensson — APPROVED** [review]
LGTM!

**Comment by MartinZikmund** [comment]
Wow, that was fast! Thanks @patriksvensson!

**Comment by 0xced** [comment]
How about exposing a `StringComparison` property directly (that would default to `StringComparison.CurrentCulture`) instead of a `bool` property? So that it would be possible for the user to choose `InvariantCultureIgnoreCase` or  `OrdinalIgnoreCase` too?

**Comment by MartinZikmund** [comment]
That is a neat idea. It would be a breaking change, but as it was a recent addition, I guess only Uno.Check is currently using it, what do you think @patriksvensson ?

**Comment by 0xced** [comment]
Given it was introduced last week in a **preview** version of a library which has not reached a stable 1.0 version I think it should be fine. But the final decision is up to the maintainers of course.

**Comment by patriksvensson** [comment]
@MartinZikmund @0xced Sounds like a good idea to me!

**Pull request merged**
