### PR TITLE
Add new VerticalBarChart Widget

### PR DESCRIPTION
**Pull request by pitermarx**
A 80% done feature of showing a chart.

imagem

```
new VerticalBarChart()
            .SetHeight(10)
            .SetColor(Color.Orange1)
            .SetData(new double[] { -4, -2, 0, -1, -2, 4, 2, 0, 1, 2, 3, 4, 5, 6 });
```

The major thing it is missing is that the chart only is as wide as the data.

1 datapoint <-> 1 character

I think it should be able to expand to the available width

Is it worth pursuing?

### CODE REVIEW

**Comment by pitermarx** [comment]
@microsoft-github-policy-service agree

**Comment by pitermarx** [comment]
Are there more fine grained unicode chars for the bar height?

**Comment by nils-a** [comment]
@pitermarx for my mental health: We added a PR-Template on 2023-09-27, and you created this PR on 2023-09-28. Did you remove the content of the PR template?

**Comment by pitermarx** [comment]
I created the PR by opening the source in https://github.dev/spectreconsole/spectre.console
and then commiting the changes. it asked me if I wanted to do a PR

**Comment by nils-a** [comment]
And there was no text in the description to be filled?

**Comment by pitermarx** [comment]
nop

**Comment by pitermarx** [comment]
do you want me to cancel this and create a ticket first?

**Comment by nils-a** [comment]
That would be really nice of you!

**Pull request closed without merging**
