### PR TITLE
Add in return for Abort on MultiSelectionPrompt

### LINKED ISSUE #851: Esc Key to exit selection
There is an "Abort" input selection, but it is not used.
https://github.com/spectreconsole/spectre.console/blob/eb6a9d8d047266b1317cdbed87c35f68996b9f0f/src/Spectre.Console/Prompts/List/ListPromptInputResult.cs#L8

Optionally tie that to the Esc Key, so that you can have nested menus.

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
Fixes #851

### CODE REVIEW

**Comment by BenjaminMichaelis** [comment]
@patriksvensson To follow up with my question on this issue, is this all you are looking for a return of the Result? Or also some handling of some sort?

**Comment by patriksvensson** [comment]
@BenjaminMichaelis 

We call `HandleInput` from here: https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Prompts/List/ListPrompt.cs#L59

1. We would need to add a check here for the `Abort` result, and in that case, break.
2. We should probably add a new `required` boolean to the `ListPrompt.Show` method, and before aborting, check if we're allowed to, so we don't abort if the prompts are expected to produce some kind of result.

What do you think?

**Comment by BenjaminMichaelis** [comment]
I think that makes sense, Let me check that I fully understand what you mean by trying to implement it

**Comment by BenjaminMichaelis** [comment]
How does this look? @patriksvensson

**Comment by patriksvensson** [comment]
@BenjaminMichaelis I think it looks good! Would it be possible to add a test as well?

**Comment by patriksvensson** [comment]
The build problems should have been resolved now.
Could you rebase your PR branch against the main branch?

**Comment by BenjaminMichaelis** [comment]
Just rebased @patriksvensson, added in a small test, but as I am still getting used to this library, not positive if there are better things I should be testing for/or how to since this feels minor. I'm not positive how to get the ListPromptInputResult out from the test view since we return a state

**Comment by patriksvensson** [comment]
@BenjaminMichaelis Your test actually showed that there is a flaw in the design.
We always return the selected item(s) and in this case, we want to inform the caller that the operation was aborted.

@nils-a @phil-scott-78 Any suggestions on how we could solve this in an extendable way?

**Comment by BenjaminMichaelis** [comment]
Ahh, to make sure I am following, so the state index should still be 0 in fact like the test shows but in addition be letting the caller know that it didn't move because this was an aborted case?

**Comment by patriksvensson** [comment]
@BenjaminMichaelis Correct, but I think we need to discuss how this should be done. Would like some input from the other maintainers about this.

**Comment by patriksvensson** [comment]
@BenjaminMichaelis I'm sorry, but turns out there already is an active pull request for this item: https://github.com/spectreconsole/spectre.console/pull/711

I'm sorry I didn't realize this before, I could have saved you from wasting your time 😞

**Comment by BenjaminMichaelis** [comment]
> @BenjaminMichaelis I'm sorry, but turns out there already is an active pull request for this item: #711
> 
> I'm sorry I didn't realize this before, I could have saved you from wasting your time 😞

Aw bummer, I'll keep looking for more to do :)

**Comment by Kamakazi152** [comment]
@patriksvensson Am I looking at this right and seeing #711 was never finished? If so, could @BenjaminMichaelis submit his changes again? This feature is still not implemented, and it looks like Benjamin already got this figured out.

**Pull request closed without merging**
