### PR TITLE
add cross platform

### PR DESCRIPTION
**Pull request by wanglong126**
readme add `cross platform`

### CODE REVIEW

**Comment by Cycatz** [comment]
Looks great!

**Review by patriksvensson — APPROVED** [review]

**Comment by wanglong126** [comment]
> Looks great!

thank you

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Review by PlayerAI — COMMENTED** [review]
The contributor added a few words to emphasize the library's ability to be used cross-platform. As a Chinese person, I can confirm that.

**Comment by wanglong126** [comment]
> 贡献者添加了几句话来强调该库的跨平台使用能力。作为一个中国人，我可以确认这一点。

thank you

**Pull request merged**
